<script src="https://cdn.tailwindcss.com"></script>
<script id="tailwind-config">
tailwind.config = {
    theme: {
        extend: {
            colors: {
                'on-primary': '#ffffff',
                'on-primary-fixed-variant': '#862200',
                'surface-container-highest': '#e2e2e2',
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed-dim': '#c6c6c7',
                'on-secondary-fixed': '#191c21',
                'secondary-fixed-dim': '#c4c6cd',
                'on-secondary-container': '#606368',
                'inverse-on-surface': '#f1f1f1',
                'surface-tint': '#b02f00',
                'surface': '#f9f9f9',
                'on-error-container': '#93000a',
                'secondary': '#5c5e64',
                'on-tertiary': '#ffffff',
                'tertiary-fixed': '#e2e2e2',
                'error-container': '#ffdad6',
                'inverse-surface': '#2f3131',
                'surface-bright': '#f9f9f9',
                'on-tertiary-fixed-variant': '#454747',
                'primary': '#ac2e00',
                'surface-container-high': '#e8e8e8',
                'surface-variant': '#e2e2e2',
                'secondary-fixed': '#e1e2e9',
                'background': '#f9f9f9',
                'on-tertiary-fixed': '#1a1c1c',
                'on-error': '#ffffff',
                'surface-container-low': '#f3f3f3',
                'outline': '#916f66',
                'on-primary-container': '#fffbff',
                'on-secondary': '#ffffff',
                'tertiary': '#5a5c5c',
                'on-background': '#1a1c1c',
                'on-surface': '#1a1c1c',
                'surface-dim': '#dadada',
                'primary-fixed': '#ffdbd1',
                'on-surface-variant': '#5d4038',
                'primary-container': '#d73b00',
                'secondary-container': '#dedfe6',
                'on-secondary-fixed-variant': '#44474c',
                'on-primary-fixed': '#3b0900',
                'surface-container': '#eeeeee',
                'outline-variant': '#e6bdb2',
                'primary-fixed-dim': '#ffb5a0',
                'on-tertiary-container': '#fcfcfc',
                'inverse-primary': '#ffb5a0',
                'error': '#ba1a1a',
                'tertiary-container': '#737575',
                'bank-charcoal': '#25282D',
                'bank-orange': '#FF4800',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                gutter: '24px',
                'container-max': '1200px',
                'stack-md': '16px',
                'stack-lg': '32px',
                'stack-sm': '8px',
                'margin-mobile': '16px',
                unit: '8px',
                'margin-desktop': '40px',
            },
            fontFamily: {
                'label-bold': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'headline-xl': ['Inter', 'sans-serif'],
                'body-lg': ['Inter', 'sans-serif'],
                caption: ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
            },
            fontSize: {
                'label-bold': ['14px', { lineHeight: '16px', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '16px', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            },
        },
    },
};
</script>
